error_code_def(success, "" ),
error_code_def(certificate_invalid, "invalid certificate" ),
error_code_def(certificate_name_invalid, "certificate name invalid" ),
error_code_def(certificate_name_unknown, "certificate name unknown" ),
error_code_def(certificate_names_mismatch, "certificate names mismatch" ),
error_code_def(connection_name_unknown, "connection name unknown" ),
error_code_def(connection_name_invalid, "connection name invalid" ),
error_code_def(certificate_not_found, "certificate not found" ),
error_code_def(url_unknown, "unknown URL" ),
error_code_def(parse_file_failed, "parse file failed" ),
error_code_def(logon_username_password_invalid, "username or password invalid" ),
error_code_def(logon_account_blocked, "account blocked" ),
error_code_def(logon_failed, "logon failed" ),
error_code_def(logon_no_response, "no response" ),
error_code_def(thread_already_running, "thread already running" ),
error_code_def(socket_invalid, "invalid socket" ),
error_code_def(file_failed_copy, "failed to copy file" ),
error_code_def(unknown_error, NULL )
