#!/bin/bash
#
#

rootdir=/var/lib/uniproxy

# Create user and home
useradd -d ${rootdir} -g users -s /bin/bash -m --system uniproxy

if [ ! -e /etc/init.d/uniproxy ]; then 
	ln -s /lib/init/upstart-job /etc/init.d/uniproxy
fi


echo "useradd: $?" 1>> /tmp/uniproxy.log 2>> /tmp/uniproxy.log

service uniproxy start

echo "service uniproxy start: $?" 1>> /tmp/uniproxy.log 2>> /tmp/uniproxy.log

exit 0
