#!/bin/bash

# Stop all the services
#service uniproxy stop
#echo "service uniproxy stop: $?" 1>> /tmp/uniproxy.log 2>> /tmp/uniproxy.log

systemctl stop uniproxy.service
systemctl disable uniproxy.service

exit 0

