[Files]

;============================================================================
; WARNING! This file is autogenerated 
; WARNING! All changes made in this file will be lost!
;============================================================================

#define BUILDNUMBER "1"
#define VERSIONNUMBER "v1.6.0"

