[Files]

;============================================================================
; WARNING! This file is autogenerated 
; WARNING! All changes made in this file will be lost!
;============================================================================

#define BUILDNUMBER "127"
#define VERSIONNUMBER "v0.3.1"

