[Files]

;============================================================================
; WARNING! This file is autogenerated 
; WARNING! All changes made in this file will be lost!
;============================================================================

#define BUILDNUMBER "124"
#define VERSIONNUMBER "v0.1.1"

